server:
  port: 8081
logging:
  level:
    root: info
    org.springframework.security.oauth: trace
provider:
  port: 8083
spring:
  security:
    oauth2:
      client:
        provider:
          mock:
            authorization-uri: http://localhost:${provider.port}/auth/realms/briciam/protocol/openid-connect/auth
            token-uri: http://localhost:${provider.port}/auth/realms/briciam/protocol/openid-connect/token
            user-info-uri: http://localhost:${provider.port}/auth/realms/briciam/protocol/openid-connect/userinfo
            jwk-set-uri: http://localhost:${provider.port}/auth/realms/briciam/protocol/openid-connect/certs
            user-name-attribute: preferred_username
        registration:
          mockClient:
            client-id: bricClient
            client-secret: "7c12c7e6-454e-4c0c-a89c-522bcb4f8d00"
            provider: mock
            authorization-grant-type: "authorization_code"
            redirectUri: '{baseUrl}/login/oauth2/code/{registrationId}'
            scope:
              - openid
              - profile
              - email